language: node_js
node_js:
- '12'
sudo: false
branches:
  only:
  - master
before_script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
env:
  global:
  - ALIYUN_ENDPOINT=http://39.98.93.191/admin
  - ALIYUN_ACCESS_KEY=z1aWXyf27QaUtAAT6wv4t5sL4visgBhRBPb
  # ALIYUN_ACCESS_SECRET
  - secure: G3fszsAtfPfCOZO4CZqvJ3N7ZToU4cRXbtGCMxj+gvhlT8Ct4zg9jIqzVWV+l/3yhv9nQkwZnWARv5t6ekZpMZeugGbzgQOoFgsNFhTnanNHJvJ0TauYFW/sUCiVIOCL0f7QZv8tFPoUxxtZzjdY04L7gmbplI4gvcQ4Enu7gd8B7ijil+IQnjfGB8opDOJX4roGkmre35kyTEUAL3p4dG53WT0o64uM7eSTOwtHBa+QNyL+o1U37iKL0cmLnA0G7T3yTx78OKbGWdwODPp0yDO1LWyGZa+3Ezz0Z5SHsLJVRnupluxpsJg6hR4OPgY3QABCe0mYA8YR85zPLWI/lCivyl8T2TF8IWtIgGImVkPcG+yEjejxGHy0MTcH7YYXKPmVoR7hPhPxrDfFKyDYl+ADoUx+sXQoPoYsXleogcYYTcizFhIVNaoQ+esLKuBMsR8rsW5ZLJY8oBnpMx23NKS3c7GDU7cZwoqtm1ffs8GS192ot6rcEBaEPQfKhc/6ygH/MXWd0LqNKgSIYlDjxWzHqjbi+pCjLWGBrhJGlY5LAdyWj2EiWSWwr5FStcmNw2AeAHMDP4lG3+RhoZJKG1s2wYdDH+Kzo6S0hhYh+wynFYLsihxUnSnyauphf+afvrqOTES/EVATJkkb6lF+khhcFSs/uiewdUSrb0SDjQg=
  - AWS_ENDPOINT=http://54.213.55.12/admin
  - AWS_ACCESS_KEY=z1W9k2T7XTddPMtArMs7gs6pJYvsN63dggE
  # AWS_ACCESS_SECRET
  - secure: Km//ecK0H/WXhvtUp9d5CQi3YPegUGHgefY2ykjI9AOO7aZZtroz2xuDYLtJeqTZjz304XUpk61rZv5ef1qwmYXAP3nfQ4Eaz4ZennIatqnGWvj2dQJOF06OMgxUftRG6omyLGpiX4lWd+BwUucThxrfji10ZYRkPJEAS9XiWAPPEUObuQYakEXSnAKbAftf624kw9TdITqnaPowYqKSBhMCDRBfSoIWYBXY2/oB7SQORd5Lvbu7bHw14iY5N5Ll1s+4di8r4iK+z7SBjl7XvHQ6eh1WaigS1DSRM3BS0iOZssPr6VXRp86lSVBGS9h30PIj5XU6Vh7uNeNx8klZXs3CZME8ygfEowCSmc5cNHsmllAHlOZmNbjW0JELzlTbbIypUhxMtE940DMv0ySHtvGmCgCH8DdFd92oNVeZ5uRYO70C2U4ENP52fXOjmxhQSGQpPEkgM3GMLpn241VMMUfDZx5MIjcxLaBL36PI0YiOD7IMoynV2WWv7XUqBmSUVonNP/Ve9WOcM55XihiXIwOQF7s8i7FLc/P14dNjEeDS4CGtLMn3bqGzm6Hpfa5MgpAh7BJVOz2otVaBySDuthIOJwtwCW1CRMtE1cSZXydfMCr25qi/1d8iFI7VrhpH4vUSlwSaRToTAm5gAZs/6wIj8aQ+WSFdzNk7jiLd7FQ=
  - secure: favXTvnBgT9EhVoWX6051KJ6+dgwINT8EWeg4fvNXI2LwFTnuPjtM+JZ22SrD6TisCiSP+m7piVtdlC5l0i2+MIKL2JtC3Sfd6XMAaJauZskDAXqavfZVZolbe/fyGAqAcNybV9i60jtosEJGO9oivS8yockQHUY6qi79VTBQJBB8M043RmbfPZRpAd2S00SN5agTI0AOcyLswW5nJdxKyEeNO7rk4+yK4m9tItPT6brGQNtyi0Z7Y5zMvE1rcCd/c/O9oAagCFJQhhRNG1zyb185V8Wqk/MVKaUiLeecBtAbbX4SYNnmmeVl7TXZ0a9JFvOQl0TtgFLTsXetsXr4+DcFCn8eBbdKcq7ifnZGprUHoXLUZTZ2gxdXpLxHoBJMPblAixThi/PTP9hQyrfCWhok/ksr2owxl41FsM2pg/b8d9QemhmZBNtz5vyLz2blf7XgBgLOnXxKAKTdqZ4wE8G2KdeQDAYjEzRZRKlvf6rWVLq41lheE5nzKDIKYPP4j9KrUJAvle6fedS5VcfyDnRYssL7iQTOkh2j6ZaD6PnMq7fdzbEk+l5Myey5oeuwRw9V6kYY+aZ/haskxEYHqnMrGa3kQadVHxF1l5ByB9w0xxkYkHCE+u9RxxI4HLvG2ENB3/YoMjkAsgmjfydbPk6aKhRONU6Dufzooda6Gs=
  - secure: HbNPB0SFuWlmX0yNqWBwZCbUDVZ8McLJv0m8sym/UWJ+uwackYmoME9SkxP9i6HiTOW0Axs2r6ygAXQ+m7UgqtjOvdtHo9SapdcXC61QOucxDHfw4q4ByGa8gywPpnufr3y0Rxbyht5k/biKuxjfBvshAneexH/o/z8jAoF1D8XmADepU5VrLX1LxtWFG6wOmsqQUrUvkMqwGUMyh+HSrYAo2B9aRLgQfmXieMY7+BpJZuNp2Avc3FB0dnwbECEmBJ/B0XEM5Hcy3K1nCvZAVvWFP+eeWAzSWxtGju7dh/19Dq3gP/Y9KNnlMH2etQZwg24sh1/1ZofzKG1YlMoigYtovSkpjGtukM84xi3WBy97ByxhJuqiibw42K/f2ahGB58gEf8ZQ+8zcwLadQ62cjj2FQuEMoE/KG+7oIrYaTwXIpGL0rLKT9vW0kS2yhSqEoW1HuY3bSzbSxYhzQ0zaShons8uJ1LLWlABwwQ+uMnuJqeWqNJqhITxW6WEchhtUzoQjlucf1C7G6YbDri0vOkXOoWv+9aZh72nvsFVHx28lB/7eGb0CnDq6cCixOXIxhJzThk38wgAPtcuETe25TSbYCPKbKZYiECU6QcnSOgiq+lSlZ8AaLDfSCpnUxnPBjAcVRlwv4b+DZrVvpM+4dewKYeaEmcRaeZaN/1ct60=
