language: node_js
node_js:
- '12'
sudo: false
branches:
  only:
  - master
before_script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch: master
env:
  global:
    secure: oCX6gXycupBsck7gs5SOcJPcDUdrh8j6watg3no+TO7JTmRUL0/La26u9nevgZGsSs9mw+WQmGJF8bogKaKDZTCXmifmD947IXvYFIWZVePuz5uubxGpOP8NaUb/nFeuCfwjumSkYBNgEQeRnq8s+OiR2Xq7DAUdnWnOZ5cijaNhGzllkhT9anJTBRkyEvwXRQcEBf9ocJ3wisyAcnj1nTnG0tIOhXxOgCo/8GfTXiPhmnN3NDUIocjni1PEmcWlw0a4wxuv09lWFPyDfDnz9U1I0KqeYrqIJnMQeQIU4L7K9sXdUQRu2nT7XpnmlAq31Kd/8rczIeuYEEeQmmYz9N12rUj4xaSZYeC7vbh5/HRT6gLQC8TAqoH0UZR8PuYnjfB2bfsZm8rr13lJb7ERvaUy+lj1W8oQkeuwmNHV0DH6J8OfUQW8TrrBk4gkVWFInU3ZLQlY9mmBQ2AKgE+Sl8UCfgt7QtHhvdMSqdQFD8rvis7te512qm5R6rdsMgBQ2Anr7aM0LbkhHHrCpZ6SVdm2jkF8hyGhqfIOGggb9sad/sw8riAShjSzSla19qkFIQ5fErRab+cOaSs/hytmjNcRxlq9WeGWIKbPzQ7s3/m/GSgViiH05Y/wVh3Lwzn2OKdpMatCRcG2Z0m4RXJEZY5f7zIDmLiLPnGAtapDuwk=
