language: node_js
node_js:
- '12'
sudo: false
branches:
  only:
  - master
before_script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
env:
  global:
  - secure: favXTvnBgT9EhVoWX6051KJ6+dgwINT8EWeg4fvNXI2LwFTnuPjtM+JZ22SrD6TisCiSP+m7piVtdlC5l0i2+MIKL2JtC3Sfd6XMAaJauZskDAXqavfZVZolbe/fyGAqAcNybV9i60jtosEJGO9oivS8yockQHUY6qi79VTBQJBB8M043RmbfPZRpAd2S00SN5agTI0AOcyLswW5nJdxKyEeNO7rk4+yK4m9tItPT6brGQNtyi0Z7Y5zMvE1rcCd/c/O9oAagCFJQhhRNG1zyb185V8Wqk/MVKaUiLeecBtAbbX4SYNnmmeVl7TXZ0a9JFvOQl0TtgFLTsXetsXr4+DcFCn8eBbdKcq7ifnZGprUHoXLUZTZ2gxdXpLxHoBJMPblAixThi/PTP9hQyrfCWhok/ksr2owxl41FsM2pg/b8d9QemhmZBNtz5vyLz2blf7XgBgLOnXxKAKTdqZ4wE8G2KdeQDAYjEzRZRKlvf6rWVLq41lheE5nzKDIKYPP4j9KrUJAvle6fedS5VcfyDnRYssL7iQTOkh2j6ZaD6PnMq7fdzbEk+l5Myey5oeuwRw9V6kYY+aZ/haskxEYHqnMrGa3kQadVHxF1l5ByB9w0xxkYkHCE+u9RxxI4HLvG2ENB3/YoMjkAsgmjfydbPk6aKhRONU6Dufzooda6Gs=
  - secure: KlaM41aM1Moen5+XH0fSZlTXwTJZj2cb1tqJnWq4eCYyGXCApErFMUsHyWO/dDNZrU/EKVlsqtGBQHHlhPgtuAq/sHg08CjpEWRaJ6e5ACAICqL8ZCCeAWjfA/2CixrOBC9X4zTatBrEoPZTGIfrzOt6fb6HzHRqAUW3RAhm2fx3Focz2iZeznbNV66ttzSnC7xs6eMly+qRoLyfhg3n2BvgOQIqWuv6ARzSu2gZF87DryZkcy1COHwGkeWOnnJVfDfp7t9mMaw9x4N6IjvwWb9Ox40k30q8LmT4sl7CphycXklpV1EYQI0LErq4vDaOH9l7mA59+sQpQnh7Y4H9vUdk5kyJMO9bJzM9U1tRn+pQIwL4MtW/FJRLY0PDpQPKx1y3pwaVWykzb4R77gKOSzQAxqhEPsljraCifcdrJqG7f3MeHMt4JsUbIhjr3jgmyYuoyaxX9p5msK6IgVwfzeYq/bRQuRWYBq2erYFp4Al9yKHyPyq/kwm/1pg822krfBvjRmrpBY31/N2+fjFvDF8ZGwUke/K6g+TvHIzGp+W89GICK1MGc7iZNXc89Ab2UhXPrQ5dN5Fo02j3ckBOivyVpFMX9PSHv3AOmglx5RpDnpvqA+XUA9sei+tPvd34iKy8TKX1O/bA74myC7AIK2qM9CtD+tjjwrb+ZxNqSqw=
