language: node_js
node_js:
- '12'
sudo: false
branches:
  only:
  - master
before_script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
env:
  global:
  - secure: favXTvnBgT9EhVoWX6051KJ6+dgwINT8EWeg4fvNXI2LwFTnuPjtM+JZ22SrD6TisCiSP+m7piVtdlC5l0i2+MIKL2JtC3Sfd6XMAaJauZskDAXqavfZVZolbe/fyGAqAcNybV9i60jtosEJGO9oivS8yockQHUY6qi79VTBQJBB8M043RmbfPZRpAd2S00SN5agTI0AOcyLswW5nJdxKyEeNO7rk4+yK4m9tItPT6brGQNtyi0Z7Y5zMvE1rcCd/c/O9oAagCFJQhhRNG1zyb185V8Wqk/MVKaUiLeecBtAbbX4SYNnmmeVl7TXZ0a9JFvOQl0TtgFLTsXetsXr4+DcFCn8eBbdKcq7ifnZGprUHoXLUZTZ2gxdXpLxHoBJMPblAixThi/PTP9hQyrfCWhok/ksr2owxl41FsM2pg/b8d9QemhmZBNtz5vyLz2blf7XgBgLOnXxKAKTdqZ4wE8G2KdeQDAYjEzRZRKlvf6rWVLq41lheE5nzKDIKYPP4j9KrUJAvle6fedS5VcfyDnRYssL7iQTOkh2j6ZaD6PnMq7fdzbEk+l5Myey5oeuwRw9V6kYY+aZ/haskxEYHqnMrGa3kQadVHxF1l5ByB9w0xxkYkHCE+u9RxxI4HLvG2ENB3/YoMjkAsgmjfydbPk6aKhRONU6Dufzooda6Gs=
  - secure: iz9xaHBGDbgDd/HwZieyc/NQepzZ0B9BGpz4xm9d8S29vfdwfoxeucSgb8u0n0HBsJHXyDVzFtuJwwqUol5Q1sJkspWizqxg0uO4oiyEqYnsT5TwxzoxD1EaZBfH1tvKPq2R4VKaMkwCNbQV1GokFEuLJKbMgzmG3qlvzbfChno7DwAXmoK8jVt5Xm8hsijbCJXcxzU849QuhDcPDMgJ+uj/Psmt9dPC1wJBVWRrW/9T3AuSY+UL/mdOUT1kmN+jysk1Fr2vV0VLWrnMSbRvXQaO6pKj/5sTNZkQFRzl9WHJbQp5OfEIscHK5yhLdvMlBe+xJKjQzL8TlqW5r2qkMNXpZSotRjYooB9Q4WLCKckXElkokDj6qDUuRjimCxNrAnSXCXmXRtX8kaKoFmiL5pvib1nZg2SoThKMaPyNHFzp/vRhDYI68H2P4U1NPp+RSj2ayt08t/VFKMXd8wIhabmi6SiWpxKNgnSrFE13dPigl1lDN1yUR3v8vbO+FAdgihDBTaftz/UtNBt3EbMytdZI8n7V/msPAWKlChV4hT6wLYJaz0BvWoxWCKrYdZHPnMpi6PCsHkYWUlwUVTAnhAUBJDCRJmaoz0FZ7PAdq69SCqul+/H0f9q+kZhmgGrU3bI/ovwnLEAkUMYobJBa3I2uFMBBo/vpgIzEsWDjNOE=
