language: node_js
node_js:
- '12'
sudo: false
branches:
  only:
  - master
before_script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
env:
  global:
  - secure: favXTvnBgT9EhVoWX6051KJ6+dgwINT8EWeg4fvNXI2LwFTnuPjtM+JZ22SrD6TisCiSP+m7piVtdlC5l0i2+MIKL2JtC3Sfd6XMAaJauZskDAXqavfZVZolbe/fyGAqAcNybV9i60jtosEJGO9oivS8yockQHUY6qi79VTBQJBB8M043RmbfPZRpAd2S00SN5agTI0AOcyLswW5nJdxKyEeNO7rk4+yK4m9tItPT6brGQNtyi0Z7Y5zMvE1rcCd/c/O9oAagCFJQhhRNG1zyb185V8Wqk/MVKaUiLeecBtAbbX4SYNnmmeVl7TXZ0a9JFvOQl0TtgFLTsXetsXr4+DcFCn8eBbdKcq7ifnZGprUHoXLUZTZ2gxdXpLxHoBJMPblAixThi/PTP9hQyrfCWhok/ksr2owxl41FsM2pg/b8d9QemhmZBNtz5vyLz2blf7XgBgLOnXxKAKTdqZ4wE8G2KdeQDAYjEzRZRKlvf6rWVLq41lheE5nzKDIKYPP4j9KrUJAvle6fedS5VcfyDnRYssL7iQTOkh2j6ZaD6PnMq7fdzbEk+l5Myey5oeuwRw9V6kYY+aZ/haskxEYHqnMrGa3kQadVHxF1l5ByB9w0xxkYkHCE+u9RxxI4HLvG2ENB3/YoMjkAsgmjfydbPk6aKhRONU6Dufzooda6Gs=
  - secure: ZUSv5kpTWb7NY7YBaZOReQITC/3c3aMsw+qKJbUEZ1FUmfE/GFd+knfZP3N69uFvJfhoQktfPhTTTO4lJ2pDZcn8bD3aDV/pthhQSrswIoRyOJCTAmoxEG8xNP8xcNDbsWqRtAr4TWWORC5kZBkkI6Y3ilTS1a3UwcR8uIwvDEZvsPNJdW43xR2p6mowjcsg0YlCIQ2uzZRctJvsboZhv4xkl1dMyB36wKscirvnbcW902WIRQ5MjQMPjZe9yTN4DuinB/ESVH0PyrWQC1YAmqkKVN8dgdrZqNpcp1YS2RytRgEs5KL0+leRYEVSsAucCo8YJXrZK9DPd0AqgUimTVwQyqjtSBopops7Egr+NGukPhaIZEHqOoeTWcvyJrtBwrAU5UyBTofjr4CHo7K2/Pa5VsKEh08DJWcdhBqQTq6p4cjlpiP8P1VHs/oEGIT23CqnrMYKEChE5TAtuX/en3cT5+6io4WG/xAykoZMhtoMZQdoBIxycWgbvcMlbwaz3VSfdkNHdpLs108b17dOBNSXeKTR9irA8w2NOI70U0zwKRR9Njonndq3bEFalFP4pX7HScqptgw/TYStfLNYBF4QvIUJlN5X0eIPCmT2nEV4sE9Q5dj3OaQnZ2IKIxmM21kWnUC24t1pAVIhGe1Ho636l1g+SMGBbF/GxQ0DpNY=
